import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {GetStaticProps} from "next";
import {PropsWithChildren} from "react";
interface Recips{
  title:string
}

interface HomeProps{
  data:{
    recipes:Array<Recips>
  }
}

export default function Home(props:PropsWithChildren<HomeProps>) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.data.recipes.map(recipes =>{
        return <div key={recipes.title}>{recipes.title}</div>
      })}
    </div>
  )
}

export const getStaticProps:GetStaticProps = ()=>{
  return{
    props:{
      data:{
        recipes:[{title:"Pineaple Smoothie"}]
      }
    }
  }
}
