import Head from 'next/head';
import Link from 'next/link';
import { sanityClient, urlFor } from "../lib/sanity";
import { GetStaticProps } from "next";
import { PropsWithChildren } from "react";



interface HomeProps {
  recipes: {
    _id: string
    name: string
    slug: {
      current: string
    }
    mainImage: string
  }[]
}

const recipesQuery = `*[_type=="recipe"]{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home(props: PropsWithChildren<HomeProps>) {
  const { recipes } = props;
  return (
    <div >
      <Head>
        <title>Terry's Kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to Terry's Kitchen</h1>
      <ul className="recipes-list">
        {
          recipes && recipes.map(recipe => {
            return (
              <li key={recipe._id} className="recipe-card">
                <Link href={`/recipes/${recipe.slug.current}`}>
                  <a>
                    <img src={urlFor(recipe.mainImage).url()} alt="" />
                    <span>{recipe.name}</span>
                  </a>
                </Link>
              </li>
            )
          })
        }
      </ul>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const recipes = await sanityClient.fetch(recipesQuery)
  return {
    props: {
      recipes,
    }
  }
}
